name: Generate README Stats

on:
  schedule:
    - cron: "0 * * * *" # يحدث كل ساعة
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
